INSERT INTO `proj_gtn_tmp`.`t_ptp_s1a_bw_fi_zocwcs02l_cdl_deduplication_dwd`
SELECT
zwc_cmpy,
vendor,
ac_doc_no,
z_blart,
ref_doc_no,
doc_date,
doc_currcy,
sum(cast(deb_cre_dc as decimal(20,8)) ) as amount_in_doc_courr,
loc_currc2,
deb_cre_l2 as amount_in_loc_curr_2,
sum(cast(zamtusd as decimal(20,5) ))as  amount_in_usd,
clr_doc_no,
pmnttrms,
datediff(bline_date,clear_date) as `day_1`,
clear_date,
netduedate,
bline_date,
pstng_date,
zsgtxt,
null,
fi_dbcrind,
zpostby,
concat(vendor,zwc_cmpy,fiscyear),
bus_area,
null,
gl_account,
null,
null,
alloc_nmbr,
null,
null,
null,
zadd_tx,
null,
DATE_FORMAT(CURRENT_TIMESTAMP, 'yyyyMMddhhmm'),
DATE_FORMAT(CURRENT_TIMESTAMP, 'yyyyMMddhhmm') ,
'proj_gtn_tmp.t_ptp_bw_fi_zocwcs02l_cdl_deduplication_ods' as `dw_sourc_table`
FROM
  `proj_gtn_tmp`.`t_ptp_bw_fi_zocwcs02l_cdl_deduplication_ods` 
  WHERE vendor<>''
  and clr_doc_no not like '07%' and clr_doc_no not like '08%' and clr_doc_no not like '19%'
GROUP BY zwc_cmpy,
vendor,
ac_doc_no,
z_blart,
ref_doc_no,
doc_date,
doc_currcy,
loc_currc2,
deb_cre_l2,
clr_doc_no,
pmnttrms,
datediff(bline_date,clear_date),
clear_date,
netduedate,
bline_date,
pstng_date,
zsgtxt,
fi_dbcrind,
zpostby,
concat(vendor,zwc_cmpy,fiscyear),
bus_area,
gl_account,
alloc_nmbr,
zadd_tx;