CREATE TABLE IF NOT EXISTS `proj_gtn_tmp`.`t_ptp_s3u_gp_zt_kt_sq_invoice_summary_dwd`
(
`company_code` string,
`clear_date` string,
`vendor` string,
`province` string,
`city` string,
`amount_in_local_currency` string,
`comments` string,
`clearing_team` string,
`currency` string,
`amount_in_usd` string,
`accelate_payment` string,
`accelate_payment_due_date` string,
`expected_payment_proposal_date` string,
`payment_term` string,
`days` string,
`sla_result_timeliness` string,
`exclusion_timeliness` string,
`exclusion_reason_specific_work_level_timeliness` string,
`exclusion_reason_general_contract_level_timeliness` string,
`exclusion_approved_by_timeliness` string,
`sla_result_accuracy` string,
`miss_type` string,
`exclusion_accuracy` string,
`exclusion_reason_specific_work_level_accuracy` string,
`exclusion_reason_general_contract_level_accuracy` string,
`exclusion_approved_by_accuracy` string,
`dw_create_on` string,
`dw_last_update` string,
`dw_source_table` string
)
STORED AS PARQUET;