CREATE TABLE `proj_gtn_tmp`.`t_ptp_s1a_bw_fi_zocwcs02l_cdl_deduplication_dm`
(
`company_code` string,
`vendor` string,
`document_number` string,
`document_type` string,
`reference` string,
`document_date` string,
`document_currency` string,
`amount_in_doc_curr` string,
`local_currency_2` string,
`amount_in_loc_curr_2` string,
`amount_in_usd` string,
`clearing_document` string,
`payment_term` string,
`days` string,
`clearing_date` string,
`accelate_payment` string,
`accelate_payment_due_date` string,
`expected_payment_proposal_date` string,
`actual_proposal_run_date` string,
`sla_result` string,
`tat_miss_type` string,
`exclusion_timeliness` string,
`exclusion_reason_specific_work_level_timeliness` string,
`exclusion_reason_general_contract_level_timeliness` string,
`exclusion_approved_by_timeliness` string,
`accuracy_sla_result` string,
`miss_type` string,
`exclusion_accuracy` string,
`exclusion_reason_specific_work_level_accuracy` string,
`exclusion_reason_general_contract_level_accuracy` string,
`exclusion_approved_by_accuracy` string,
`dw_create_on` string,
`dw_last_update` string,
`dw_source_table` string
)
STORED AS PARQUET;