CREATE TABLE IF NOT EXISTS `proj_gtn_tmp`.`t_ptp_s1a_bw_lcfc_fbl1n_dwd`
(
`company_code` string,
`vendor` string,
`document_number` string,
`document_type` string,
`reference` string,
`document_date` string,
`document_currency` string,
`amount_in_doc_curr` string,
`local_currency_2` string,
`amount_in_loc_curr_2` string,
`amount_in_usd` string,
`clearing_document` string,
`terms_of_payment` string,
`days_1` string,
`clearing_date` string,
`net_due_date` string,
`baseline_payment_dte` string,
`posting_date` string,
`text` string,
`payment_block` string,
`debit_credit_ind` string,
`user_name` string,
`object_key` string,
`business_area` string,
`entry_date` string,
`gl_account` string,
`cost_center` string,
`profit_center` string,
`assignment` string,
`vendor_name_1` string,
`tax_code` string,
`pmt_meth_supplement` string,
`document_header_text` string,
`doc_status` string,
`dw_create_on` string,
`dw_last_update` string,
`dw_source_table` string
)
STORED AS PARQUET;